### ISSUE TITLE
Start day of week - Sunday & Monday

### ISSUE THREAD

**Issue by Robinjoeh** [gregzhang616/jquery-datepicker#1]
Hello!

Have you planned on adding start day of week to this plugin? Currently, it is only possible to start weeks on a Sunday, however most parts of the world start on a Monday.

Thoughts? :) Good job!

**Comment by gregzhang616** [comment]
Hello @Robinjoeh !
Thank you for your suggestion, I will fix this problem as soon as possible.

**Comment by Robinjoeh** [comment]
Sounds awesome! :)

Another question, isn't it possible to select dates which are not possible to click? Lets say you have a calendar for available meetings, and you have a meeting set 10 - 15th of March, to disable some days?
